### ISSUE TITLE
edge effect issue minmax_location_discrete

### ISSUE THREAD

**Issue by scpalbright** [blond-org/blond_common#18]
maths.calculus.minmax_location_discrete fails if there is a maximum or minimum at the edge.

```
    indexes_max = f_derivative_zeros[
        f_derivative_second[f_derivative_zeros] < 0]
    interp_max = 0.5+1/np.pi*np.arctan(
        (f[indexes_max+1]-f[indexes_max]) /
        (x[indexes_max+1]-x[indexes_max]))
```

Raises and IndexError if indexes_max+1 == len(f).  The same will be true for indexes_min if there is a misplaced minima.

Could be solved by excluding maxima and minima too close to the edge or by changing the indexing in that event.

**Comment by alasheen** [comment]
**Should now be corrected in the 387e4d9 commit**

The problem were the lines:

`f_derivative = np.interp(x, x_derivative, f_derivative)`
`f_derivative_second = np.interp(x, x_derivative, f_derivative_second)`

which I though I corrected ages ago but are still here...

The f_derivative should have one element less than f -> indexes_max+1 should therefore never be == len(f).

There should also never be a min/max at the edge since the function needs to ensure that the derivative is crossing 0 and needs at least 2 elements to do so. If a min/max is expected at the edges, more margin on (x,f) is needed to effectively see the min/max.

With no further comment I'll close the issue.
