### ISSUE TITLE
Not all wells found

### ISSUE THREAD

**Issue by scpalbright** [blond-org/blond_common#22]
Looking for potential wells with multiple present buckets, not all are found (see figure).

Should be reproducible with:
```
    volts = [0, 8E3, 8E3]
    harms = [1, 3, 6]
    phases = [np.pi]*3
    
    time, vWave = rf_voltage_generation(1000, 1E-6, volts, harms, phases)   
    pTime, pWell, factors = rf_potential_generation_cubic(time, vWave, -1, 1, 1E-6, 0)
    maxLoc, maxVal, inMax, minLoc, minVal = find_potential_wells_cubic(pTime, pWell)
    
    plt.plot(pTime, pWell - np.min(pWell))
    for m in maxLoc:
        for n in m:
            plt.axvline(n)
    plt.show()
```

![image](https://user-images.githubusercontent.com/11768875/63339094-72a32e00-c344-11e9-9e59-cb8bac7b0107.png)

**Comment by alasheen** [comment]
This is not a bug you need to use the "mest" option in find_potential_wells_cubic and give a estimate of the number of min/max you expect. See https://blond-org.github.io/blond_common/_modules/rf_functions_multiRF.slides.html#/9 .

I didn't include an estimate based on the harmonic number since it may lead to performance issues, but this could certainly be done. I will add an entry it the to Issue #17.
