### ISSUE TITLE
interp_time in RingOptions.__init__ and RingOptions.reshape_data

### ISSUE THREAD

**Issue by scpalbright** [blond-org/blond_common#30]
Is there a need for the interp_time to be passed to both the objects __init__ function, and the reshape_data function where it gets used?  At the moment the _ring_ object takes a _RingOptions_ object and passes the interp_time from _RingOptions_ to _RingOptions.reshape_data_.

Can it be made into either a variable in the reshape_data function, OR an input at object creation?

**Comment by htimko** [comment]
Due to the interdependence of energy and time, the Ring object needs to create first the interpolated momentum programme iteratively together with interp_time, and then uses this array to interpolate the alpha_* arrays.  

In principle, Ring only needs self.cycle_time, and interp_time could be hidden in RingOptions.

**Comment by scpalbright** [comment]
Ok, I'll remove it as an input to RingOptions.reshape_data in my current development and include that in the next pull request.
